// The craft — drafting, pleading, advocacy, evidence. Practical
// reminders rather than statements of law, so they stay true whatever
// the amendment of the week says. 150 entries.

export const CRAFT = [
  'Draft it as though the judge reads only this page.',
  'Plead facts. Argue law. Never let the two share a paragraph.',
  'If a sentence needs reading twice, the other side will read it their way.',
  'Cite the section, then the sub-section. Vagueness reads as weakness.',
  'Limitation is the first thing the other side checks. Check it first.',
  'A prayer clause that asks for too much invites a refusal of everything.',
  'Number your paragraphs. The court will refer to them by number.',
  'Attach the document you rely on. An assertion is not an exhibit.',
  'Verification is not a formality. An unverified pleading is a gift to the defence.',
  'Read the impugned order once more before you settle the grounds.',
  'Dates in the cause title, the synopsis and the affidavit must all agree.',
  'Write the relief first. Then write only what earns it.',
  'A good notice makes the suit unnecessary. Write it that way.',
  'If you cannot state the cause of action in one sentence, you do not have it yet.',
  'Every allegation needs a paragraph. Every paragraph needs a document.',
  'Name the parties the way the cause title names them, every single time.',
  'The synopsis is read first and written last. Give it the time it deserves.',
  'A chronology of dates does more work than three pages of narrative.',
  'Never plead evidence. Plead the fact the evidence will prove.',
  'One issue per paragraph. The court is reading fast.',
  'Adjectives persuade nobody on the bench. Dates and documents do.',
  'If the relief is discretionary, tell the court why discretion should run your way.',
  'Say what the other side did, then say which provision it breached. In that order.',
  'The strongest ground goes first. The court may not reach the fourth.',
  'A ground of appeal that merely disagrees is not a ground of appeal.',
  'Quote the impugned finding verbatim before you attack it.',
  'When you cite a judgment, cite the paragraph. Nobody will hunt for it.',
  'Distinguish the case against you before the other side relies on it.',
  'A precedent from a coordinate bench binds. Say so, and say which bench.',
  'Check whether the authority you are citing has since been overruled.',
  'An interim application should be capable of being granted in two minutes.',
  'State the balance of convenience in terms of what will be lost, concretely.',
  'Irreparable injury means injury money cannot repair. Show why money cannot.',
  'A prima facie case is not a strong case. Do not overclaim at the interim stage.',
  'The undertaking you offer is often what wins the injunction.',
  'Draft the order you want the court to pass, and hand it up.',
  'If you seek an ex parte order, disclose everything. Suppression undoes it later.',
  'A caveat is cheap. Not filing one is expensive.',
  'Serve properly, and prove service. Half the delays in India are service.',
  'The affidavit swears to facts, not to submissions. Keep argument out of it.',
  'Do not verify on information and belief what you actually know.',
  'A power of attorney holder can only depose to what they personally know.',
  'Exhibits should be paginated and indexed before you leave the office.',
  'The index is the first thing the court reads. Make it accurate.',
  'If a document is in the vernacular, file the translation with it.',
  'Certified copies matter. Photocopies of certified copies do not.',
  'Mark the passage you will rely on. Do not make the court find it.',
  'Written submissions should be shorter than your oral argument, not longer.',
  'A reply that answers every paragraph seriatim is harder to ignore.',
  'Denial must be specific. A general denial admits more than you think.',
  'Plead in the alternative openly, not by implication.',
  'Set out the jurisdiction clause before anyone asks about jurisdiction.',
  'Value the suit correctly. Undervaluation returns the plaint months later.',
  'Check court fees before filing, not at the counter.',
  'If there is a statutory notice period, plead compliance in its own paragraph.',
  'Pre-institution mediation, where mandated, belongs in the plaint as a fact.',
  'Where a special statute applies, say so in the first paragraph.',
  'A relief you did not pray for is a relief you will not get.',
  'Ask for costs. Then justify them.',
  'Interest: plead the rate, the period, and the basis. All three.',
  'When you amend, show the amendment. Courts dislike silent rewrites.',
  'A rejoinder is for answering new matter, not for repeating the plaint.',
  'Cross-examine on the document, not on the witness’s character.',
  'Put your case to the witness. What is not put is taken as accepted.',
  'One question, one fact. Compound questions invite compound answers.',
  'Never ask a question in cross to which you do not know the answer.',
  'Stop when you have the answer. The next question usually loses it.',
  'A hostile witness is not a lost witness. Read the whole deposition again.',
  'Contradictions must be proved by putting the previous statement to the witness.',
  'Mark the omission at the time. It cannot be argued later if it was not marked.',
  'Examination-in-chief by affidavit still needs the witness to prove documents.',
  'An expert speaks to opinion. Get the facts on which the opinion rests.',
  'A document proves itself only where the law says so. Otherwise, prove it.',
  'Secondary evidence needs a foundation. Lay it before you tender it.',
  'Electronic records need a certificate. Get it before the hearing, not during.',
  'A photograph proves what it shows, not what you say it means.',
  'Admissions in pleadings are the cheapest evidence in the case. Use them.',
  'If a fact is not disputed, get it recorded as not disputed.',
  'Frame issues carefully. Badly framed issues lose good cases.',
  'The burden of proof matters most when the evidence is evenly balanced.',
  'A presumption is rebuttable unless the statute says it is not. Check which.',
  'In cheque bounce matters the notice is the whole case. Read it four times.',
  'Compute limitation from the correct starting point, not from when you were briefed.',
  'Condonation of delay needs a day-by-day explanation, not a paragraph of regret.',
  'Where you seek review, say what error is apparent on the face of the record.',
  'A writ is not an appeal. Frame it as an illegality, not a disagreement.',
  'Alternative remedy will be raised against you. Answer it in the petition.',
  'For mandamus, plead the demand and the refusal. Both are essential.',
  'Delay defeats equity. Explain yours before the court raises it.',
  'In service matters, the rule and the circular both matter. Annex both.',
  'For a company matter, check the articles before you check the law.',
  'In arbitration, the clause is the jurisdiction. Reproduce it in full.',
  'Read the contract twice before you read a single case on it.',
  'A recital is not an operative clause. Do not rely on it as one.',
  'Definitions carry the drafting. Get them right and the rest follows.',
  'Use the same word for the same thing throughout. Elegance loses cases.',
  'Avoid "and/or". Choose one, or write both out.',
  'Every "shall" is an obligation. Count them before you sign off.',
  'A deed with an unclear schedule of property is a dispute waiting to happen.',
  'Describe immovable property by boundaries and measurement, not by name.',
  'Stamp duty is a filing question and an evidentiary one. Handle it early.',
  'Registration is not optional where the statute requires it. Check the value.',
  'An indemnity is not a guarantee. Know which one your client wants.',
  'Termination clauses are read strictly. Draft the notice period exactly.',
  'A force majeure clause protects only what it lists. List carefully.',
  'Dispute resolution clauses should name the seat, the venue and the rules.',
  'Do not leave the governing law to implication.',
  'A confidentiality clause without a term runs forever. Decide if you meant that.',
  'Non-compete clauses in India are read narrowly. Draft accordingly.',
  'In employment documents, plead the appointment letter as the primary contract.',
  'A legal notice should state the facts, the breach, the demand and the deadline.',
  'Give a real deadline in a notice. An unreal one is ignored.',
  'Send notice by a mode you can prove. Keep the tracking receipt.',
  'Reply to a notice even when the claim is absurd. Silence is quoted later.',
  'In consumer matters, plead the deficiency in service as a defined act.',
  'For an RTI appeal, quote the exact words of the reply you are challenging.',
  'A complaint should read like a chronology, not like an argument.',
  'When drafting for a lay client, read it aloud. If it trips you, rewrite it.',
  'The first line of every document should tell the reader what it is.',
  'Headings help the court. Use them, and make them accurate.',
  'A table is clearer than a paragraph whenever there are more than three figures.',
  'Round figures invite doubt. Give the exact amount and the calculation.',
  'Currency, units and dates: write them one way and stay consistent.',
  'Spell out the abbreviation the first time, then use it throughout.',
  'Do not use Latin where English will do, except where the Latin is the term of art.',
  'Delete every sentence that does not advance a fact or a ground.',
  'Read the draft once for law, once for facts, and once for typing.',
  'Print it before you file it. Errors hide on screens.',
  'Check the annexure numbering last. It is always wrong at least once.',
  'A draft is finished when removing anything would weaken it.',
  'Keep a precedent folder of your own good drafts. It compounds.',
  'When you borrow a precedent, change every name and every date deliberately.',
  'Never file a document with another client’s name still in it.',
  'The other side will read your draft more carefully than your client will.',
  'Assume the draft will be read by someone hostile and tired.',
  'If a clause can be read two ways, it will be read the way that hurts you.',
  'A short pleading well pleaded beats a long one badly organised.',
  'Do not hide the weak point in the middle. It will be found.',
  'Anticipate the first question the court will ask, and answer it on page one.',
  'Write the strongest sentence in the document first, then build around it.',
  'The opening paragraph decides how the rest is read. Rewrite it last.',
  'Give the court a reason to decide in your favour that it can write down.',
  'Judges are drafting an order while you speak. Give them the words.',
  'A concise submission is a courtesy that is repaid.',
  'Never overstate an authority. It will be read from the bench.',
  'If you must concede, concede early, clearly, and move on.',
  'Prepare a one-page note of dates for every hearing. It saves you every time.',
  'Take the file, not the memory, to court.',
  'Know the number of your own matter before it is called.',
  'When in doubt, ask for a short adjournment rather than argue unprepared.',
]
