// For the mornings that need it. Written plainly — no slogans, and
// nothing that would embarrass someone reading it on a bench outside
// court. 160 entries.

export const HEART = [
  'You did not choose an easy profession. You chose a necessary one.',
  'The file that frightens you most is the one that will teach you most.',
  'A hearing you dread today is a precedent you will cite tomorrow.',
  'Somebody is sleeping better tonight because you read the file twice.',
  'You are allowed to be new at this. Everyone arguing today once was.',
  'An adjournment is not a defeat. It is more time to be right.',
  'The client remembers how you listened long after they forget the section.',
  'Losing a matter you fought honestly costs less than winning one you did not.',
  'Courage in court is mostly preparation, arriving on time.',
  'Your worst draft today is still better than the one you never wrote.',
  'Every senior you admire has stood exactly where you are standing.',
  'The quiet lawyer who knows the record wins more often than the loud one.',
  'Rest is not indulgence. A tired advocate misses the point that matters.',
  'You will not always be believed. Be right anyway, and keep the notes.',
  'The first time you argue alone your hands will shake. Argue anyway.',
  'A brief you understand beats a brief you have merely memorised.',
  'Nobody was born knowing the difference between a revision and an appeal.',
  'Your fee has not arrived yet. Your reputation is arriving every day.',
  'The judge is not your enemy. The clock is, and the record is your ally.',
  'You cannot control the outcome. You can control whether you were ready.',
  'On the days you feel like a fraud, open the file. Competence returns.',
  'One good paragraph today is worth three rushed ones tomorrow.',
  'You need not be the cleverest person in the room, only the most prepared.',
  'Being corrected in open court is how every good lawyer got good.',
  'The matter that keeps you awake is usually the one you care about.',
  'It is not weakness to say you will revert after checking. It is practice.',
  'A client who trusts you will forgive a delay. One who does not forgives nothing.',
  'Your notes from last year are a letter from a version of you who cared.',
  'Small matters make careful lawyers. Careful lawyers get big matters.',
  'There is no shame in a settlement that gives your client their life back.',
  'You are permitted to eat lunch. The docket will still be there.',
  'The senior who snapped at you today was frightened about something else.',
  'If you are still reading at midnight you have not failed. You are working.',
  'Every advocate has a matter they lost and still think about. That is conscience.',
  'The law rewards the patient more reliably than it rewards the brilliant.',
  'Nobody remembers who was fastest. They remember who was right.',
  'You joined a profession where being wrong in public is part of the training.',
  'A day spent reading is not a day wasted, whatever the billing sheet says.',
  'Your first bad order is not the end of a career. It is the start of one.',
  'It is a privilege to be the person somebody calls when they are frightened.',
  'You will one day explain to a junior what you are struggling with today.',
  'The best cross-examination you ever do will be quiet and take four minutes.',
  'Doubt before a hearing is not a warning. It is attention.',
  'Argue the case you have, not the case you wish had walked in.',
  'The record is the only witness that never forgets. Keep it well.',
  'A lawyer who admits the weak point first is the one the court believes.',
  'You need not win every argument in the room, only the one on the file.',
  'Take the matter nobody wants once a year. It will teach you more than the rest.',
  'Fear before a first appearance is not unsuitability. It is understanding.',
  'The client sees a lawyer; you see a hundred doubts. Only one of those matters today.',
  'You are building a practice one returned phone call at a time.',
  'Reputation is what the registry clerk says about you when you are not there.',
  'Kindness to opposing counsel costs nothing and is remembered for years.',
  'A concession made early is worth more than one dragged out of you.',
  'There will be years where you learn more than you earn. Those are the good years.',
  'Do not measure yourself against the loudest person in the bar room.',
  'The advocate who actually reads the statute is rarer than you would believe.',
  'You are allowed not to know. You are not allowed to guess in writing.',
  'A matter properly refused is better than a matter badly kept.',
  'Somebody once gave your senior a chance. Pass it on when you can.',
  'The hardest part is starting the draft. It always was, for everyone.',
  'When the facts are against you they are still your facts. Work with them.',
  'You do not owe a client dishonesty, however much they want it.',
  'A career is not built in one hearing. It is built in ten thousand small choices.',
  'Ask the question you think is stupid. Half the room wanted to ask it.',
  'The most useful skill in this profession is finishing things.',
  'Nobody is watching you as closely as you fear. Everybody is nervous too.',
  'The judge who was hard on you today may remember you well tomorrow.',
  'You are entitled to a life outside this. It makes you better inside it.',
  'A quiet week is when you fix the things a busy week broke.',
  'What feels like tedium today is the mastery you will rely on later.',
  'Read one judgment for pleasure this week. It is why you came here.',
  'The person you were when you took the oath would be proud of today.',
  'A settlement is not surrender. Sometimes it is the most lawyerly thing you will do.',
  'Not every matter is a cause. Some are just a family who need it to end.',
  'You will lose. Then you will read why, and you will be better.',
  'It is not arrogance to know your own worth. It is a fee note.',
  'The junior watching you today is learning how to treat people.',
  'Your handwriting in the margin of a brief is the sound of thinking.',
  'A clear head at nine in the morning is worth three hours at one at night.',
  'Answer the difficult email first. The day gets lighter after it.',
  'You are not behind. You are on a different matter than they are.',
  'Some days the only victory is that the file is in order. Take it.',
  'The court gives you minutes. Spend them on the point that decides it.',
  'A lawyer known for accuracy never has to raise their voice.',
  'You cannot argue away a bad fact. You can face it before the other side does.',
  'The client is not their case. Ask how they are before you ask for documents.',
  'Being underestimated is a tactical advantage. Do not rush to correct it.',
  'You have permission to work slowly on the thing that must be right.',
  'The seniors who last are those who kept reading after they stopped having to.',
  'Nothing in this profession is as final as it feels on the day.',
  'A good day is one where you told somebody the truth they needed.',
  'Discipline on an ordinary Tuesday is what wins the extraordinary Friday.',
  'You are learning a craft, not passing a test. Crafts take years.',
  'The most persuasive thing in the room is usually a document.',
  'When you feel outmatched, go back to the facts. They belong to you.',
  'You do not have to be fearless. You have to file on time.',
  'Somebody in this profession will be kind to you today. Notice it.',
  'The last paragraph is where most drafts are lost. Do not write it tired.',
  'Every great advocate has a folder of arguments that did not work.',
  'You will get better at this — not today perhaps, but measurably, by the year.',
  'Take the compliment from the bench. You will need it in six months.',
  'Litigation is long. Kindness to yourself is a professional skill.',
  'You are the only person who has read this entire file. That is power.',
  'Some matters end in a whimper. It does not undo the work.',
  'The point you fear the other side will take — take it yourself, first.',
  'If your client understood the draft, so will the judge.',
  'A career of small honest wins outlasts one of loud unstable ones.',
  'There is no such thing as an unimportant client meeting.',
  'You were trusted with somebody’s worst year. Handle it accordingly.',
  'The cure for feeling like a fraud is a well-indexed brief.',
  'What worries you at three in the morning is rarely what decides it.',
  'Be the lawyer your twenty-year-old self hoped to become.',
  'A steady hand helps a frightened client more than a brilliant mind.',
  'You will meet lawyers who cut corners and prosper. Do not join them for a season.',
  'A matter you understand deeply is worth three you have merely skimmed.',
  'The junior who asks good questions becomes the senior who gives good answers.',
  'Nobody has ever regretted checking the limitation period one more time.',
  'You are allowed to change your mind on a legal position. Say so early.',
  'Honesty about a weak case is the most valuable advice you will ever give.',
  'The court forgives an error of judgment far sooner than an error of candour.',
  'You are measured not by the matters you took but by how you left them.',
  'Difficult clients are still clients. Difficult conduct is still not acceptable.',
  'Write the note now. Future you will not remember what today you knew.',
  'A calm voice in a hostile hearing is a strategy, not a personality.',
  'There is dignity in a well-drafted notice only two people will ever read.',
  'You will one day be somebody’s idea of a safe pair of hands.',
  'It is enough, some days, to have not made anything worse.',
  'Do the thing you have avoided for eleven days. It takes forty minutes.',
  'A name for returning calls carries further than a name for brilliance.',
  'The law changes. The habit of reading it carefully does not.',
  'You are not competing with the bar. You are competing with your last draft.',
  'Nobody does this alone. Find one person to ask stupid questions of.',
  'What you learn on the small matter is what saves you on the large one.',
  'Do not apologise for taking the time to be correct.',
  'You have already survived every difficult day so far.',
  'Say no to one thing this week so you can say yes properly to another.',
  'The most professional thing in the world is a matter closed cleanly.',
  'Your value is not your billable hours. It is the sleep you give people back.',
  'Court is theatre for ten minutes and paperwork for ten months. Respect both.',
  'When you cannot fix the law, fix the facts you present it with.',
  'You are permitted to be proud of a good paragraph.',
  'The person across the table is doing their job too. Let them.',
  'A career is a long argument with yourself about what standard you keep.',
  'Read the impugned order once more. There is almost always one more thing.',
  'You do not need certainty to act. You need preparation and a fallback.',
  'The hearing will end. It always does. Then there is tea.',
  'One day a junior will cite something you wrote. Write accordingly.',
  'You are allowed to find the law beautiful. Most of us secretly do.',
  'It gets easier. Not lighter, but easier to carry.',
  'A profession that lets you be useful on your worst day is a rare thing.',
  'The oath you took still binds on the days nobody is watching.',
  'You are doing something genuinely difficult, and you are still here.',
  'Some hearings you win. Some you survive. Both count.',
  'Your best work is often invisible: the dispute that never happened.',
  'Preparation is the only part of this entirely within your control.',
  'Clients want the truth told kindly, not the comfortable thing told quickly.',
  'You will look back on this year as the one where you learned the most.',
  'A good lawyer knows the law. A trusted one returns the call.',
  'Do not let a bad order convince you that you did bad work.',
  'The bar is long. Pace yourself like it is a career, not a case.',
  'You are entitled to charge for expertise that took years to acquire.',
  'Anxiety before a hearing is preparation asking to be finished.',
  'A file left tidy on Friday is a gift to yourself on Monday.',
  'The point that seems obvious to you is worth stating. It is not obvious to them.',
  'You will be forgiven for not knowing. Not for pretending.',
  'Take notes as if you will be cross-examined on them. One day you might.',
  'Every matter closed well is an argument for the next one you are given.',
  'You are three careful drafts from being noticeably better at this.',
  'The advocate who prepares the other side’s argument rarely loses to it.',
  'There is no substitute for having read the whole thing yourself.',
  'A slow careful advocate ages into a great one. Speed ages into mistakes.',
  'Trust your instinct, then check it against the record.',
  'Somebody defended you once. Do it for somebody else.',
  'Difficult law is still law. Sit with it until it yields.',
  'It is not naive to believe the work matters. It is why the work is hard.',
  'The good days will not feel like enough. Write them down anyway.',
  'You are keeping a promise to somebody who has run out of other options.',
  'Be exact. Exactness is the whole of this profession’s kindness.',
]
