// Classical legal maxims, each with the gloss a junior would actually need.
// Common currency in Indian courts: they turn up in judgments, in argument,
// and in vivas. 126 entries.

export const MAXIMS = [
  { text: 'Fiat justitia ruat caelum.', attrib: 'Let justice be done though the heavens fall' },
  { text: 'Audi alteram partem.', attrib: 'Hear the other side' },
  { text: 'Ubi jus, ibi remedium.', attrib: 'Where there is a right, there is a remedy' },
  { text: 'Nemo judex in causa sua.', attrib: 'No one is a judge in their own cause' },
  { text: 'Actus non facit reum nisi mens sit rea.', attrib: 'The act does not make one guilty unless the mind is guilty' },
  { text: 'Ignorantia juris non excusat.', attrib: 'Ignorance of the law excuses no one' },
  { text: 'Res ipsa loquitur.', attrib: 'The thing speaks for itself' },
  { text: 'Ei incumbit probatio qui dicit, non qui negat.', attrib: 'Proof lies on the one who asserts, not the one who denies' },
  { text: 'Salus populi suprema lex esto.', attrib: 'The welfare of the people is the highest law' },
  { text: 'Interest reipublicae ut sit finis litium.', attrib: 'It is in the public interest that litigation come to an end' },
  { text: 'Nullum crimen sine lege.', attrib: 'No crime without a law defining it' },
  { text: 'Nulla poena sine lege.', attrib: 'No punishment without a law prescribing it' },
  { text: 'Volenti non fit injuria.', attrib: 'To one who consents, no injury is done' },
  { text: 'Actio personalis moritur cum persona.', attrib: 'A personal action dies with the person' },
  { text: 'Caveat emptor.', attrib: 'Let the buyer beware' },
  { text: 'Causa proxima, non remota, spectatur.', attrib: 'The proximate cause is looked to, not the remote one' },
  { text: 'Contra proferentem.', attrib: 'Ambiguity is read against the party who drafted it' },
  { text: 'Damnum sine injuria.', attrib: 'Loss without legal injury — and therefore without a remedy' },
  { text: 'Injuria sine damno.', attrib: 'Legal injury without loss — actionable all the same' },
  { text: 'De minimis non curat lex.', attrib: 'The law does not concern itself with trifles' },
  { text: 'Delegatus non potest delegare.', attrib: 'A delegate cannot further delegate' },
  { text: 'Doli incapax.', attrib: 'Incapable of forming criminal intent' },
  { text: 'Ejusdem generis.', attrib: 'General words take colour from the specific ones before them' },
  { text: 'Ex nudo pacto non oritur actio.', attrib: 'No action arises from a bare promise' },
  { text: 'Ex turpi causa non oritur actio.', attrib: 'No action arises from a base cause' },
  { text: 'Expressio unius est exclusio alterius.', attrib: 'To express one thing is to exclude the other' },
  { text: 'Falsus in uno, falsus in omnibus.', attrib: 'False in one thing, false in everything' },
  { text: 'Functus officio.', attrib: 'Having discharged the office, and so without further power' },
  { text: 'Generalia specialibus non derogant.', attrib: 'General provisions do not override special ones' },
  { text: 'Ubi jus incertum, ibi jus nullum.', attrib: 'Where the law is uncertain, there is no law' },
  { text: 'In pari delicto potior est conditio defendentis.', attrib: 'Where both are at fault, the defendant stands better' },
  { text: 'Nemo dat quod non habet.', attrib: 'No one can give what they do not have' },
  { text: 'Nemo debet bis vexari pro una et eadem causa.', attrib: 'No one should be vexed twice for the same cause' },
  { text: 'Noscitur a sociis.', attrib: 'A word is known by the company it keeps' },
  { text: 'Obiter dictum.', attrib: 'Said by the way, and so not binding' },
  { text: 'Onus probandi.', attrib: 'The burden of proof' },
  { text: 'Pacta sunt servanda.', attrib: 'Agreements must be kept' },
  { text: 'Per incuriam.', attrib: 'Decided through want of care, and so not binding' },
  { text: 'Prima facie.', attrib: 'On the face of it, unless displaced' },
  { text: 'Qui facit per alium facit per se.', attrib: 'He who acts through another acts himself' },
  { text: 'Ratio decidendi.', attrib: 'The reason for the decision — the part that binds' },
  { text: 'Res judicata.', attrib: 'A matter already judged cannot be reopened' },
  { text: 'Respondeat superior.', attrib: 'Let the superior answer for the acts of the servant' },
  { text: 'Stare decisis.', attrib: 'Stand by what has been decided' },
  { text: 'Sub judice.', attrib: 'Under judicial consideration' },
  { text: 'Ubi eadem ratio, ibi idem jus.', attrib: 'Where the reason is the same, the law is the same' },
  { text: 'Ut res magis valeat quam pereat.', attrib: 'Read it so the thing works rather than fails' },
  { text: 'Vigilantibus non dormientibus jura subveniunt.', attrib: 'The law assists the vigilant, not the sleeping' },
  { text: 'Actori incumbit onus probandi.', attrib: 'The burden of proof lies on the one who claims' },
  { text: 'Aequitas sequitur legem.', attrib: 'Equity follows the law' },
  { text: 'Alterum non laedere.', attrib: 'Do not injure another' },
  { text: 'Cessante ratione legis, cessat ipsa lex.', attrib: 'When the reason for a law ends, the law itself ends' },
  { text: 'Consensus ad idem.', attrib: 'Agreement on the same thing in the same sense' },
  { text: 'Contemporanea expositio est optima et fortissima in lege.', attrib: 'How a statute was understood when made is the strongest guide' },
  { text: 'Dura lex, sed lex.', attrib: 'The law is harsh, but it is the law' },
  { text: 'Ex debito justitiae.', attrib: 'As a matter of right, not of discretion' },
  { text: 'Ex parte.', attrib: 'From one side only, the other being absent' },
  { text: 'Factum probandum.', attrib: 'The fact to be proved' },
  { text: 'Factum probans.', attrib: 'The fact that proves' },
  { text: 'Fraus omnia vitiat.', attrib: 'Fraud vitiates everything it touches' },
  { text: 'Ignorantia facti excusat.', attrib: 'Ignorance of fact may excuse, where ignorance of law will not' },
  { text: 'Impotentia excusat legem.', attrib: 'Impossibility excuses compliance' },
  { text: 'In limine.', attrib: 'At the very threshold, before the merits' },
  { text: 'In personam.', attrib: 'Against a particular person' },
  { text: 'In rem.', attrib: 'Against the thing, and so against the world' },
  { text: 'Intra vires.', attrib: 'Within the powers conferred' },
  { text: 'Ultra vires.', attrib: 'Beyond the powers conferred, and therefore void' },
  { text: 'Ipso facto.', attrib: 'By that very fact, without more' },
  { text: 'Jus cogens.', attrib: 'A rule from which no derogation is permitted' },
  { text: 'Lex loci.', attrib: 'The law of the place where it happened' },
  { text: 'Lex fori.', attrib: 'The law of the forum hearing the case' },
  { text: 'Locus standi.', attrib: 'The standing to be heard at all' },
  { text: 'Mala fide.', attrib: 'In bad faith' },
  { text: 'Mens rea.', attrib: 'The guilty mind' },
  { text: 'Actus reus.', attrib: 'The guilty act' },
  { text: 'Mutatis mutandis.', attrib: 'With the necessary changes made' },
  { text: 'Nemo tenetur seipsum accusare.', attrib: 'No one is bound to accuse himself' },
  { text: 'Nova constitutio futuris formam imponere debet, non praeteritis.', attrib: 'A new law should govern what follows, not what is past' },
  { text: 'Novus actus interveniens.', attrib: 'A new intervening act that breaks the chain' },
  { text: 'Nunc pro tunc.', attrib: 'Now for then — an order given effect from an earlier date' },
  { text: 'Omnia praesumuntur rite esse acta.', attrib: 'Official acts are presumed regularly done' },
  { text: 'Pari passu.', attrib: 'On equal footing, without preference' },
  { text: 'Pendente lite.', attrib: 'While the litigation is pending' },
  { text: 'Quantum meruit.', attrib: 'As much as was deserved for work actually done' },
  { text: 'Qui prior est tempore, potior est jure.', attrib: 'He who is first in time is stronger in law' },
  { text: 'Quid pro quo.', attrib: 'Something given for something received' },
  { text: 'Ratio legis.', attrib: 'The reason behind the law' },
  { text: 'Reddendo singula singulis.', attrib: 'Referring each phrase to its own subject' },
  { text: 'Res gestae.', attrib: 'Things so bound up with the act that they form part of it' },
  { text: 'Res nullius.', attrib: 'A thing belonging to no one' },
  { text: 'Restitutio in integrum.', attrib: 'Restoration to the position before the wrong' },
  { text: 'Sine die.', attrib: 'Adjourned without a date to return' },
  { text: 'Sine qua non.', attrib: 'The thing without which it cannot stand' },
  { text: 'Suo motu.', attrib: 'On the court’s own motion' },
  { text: 'Uberrima fides.', attrib: 'Utmost good faith, owed in insurance and partnership' },
  { text: 'Verba chartarum fortius accipiuntur contra proferentem.', attrib: 'The words of a deed are read against the one who wrote it' },
  { text: 'Ad valorem.', attrib: 'According to the value' },
  { text: 'Bona vacantia.', attrib: 'Property left without an owner' },
  { text: 'Corpus delicti.', attrib: 'The body — the substance — of the offence' },
  { text: 'Cy-près.', attrib: 'As near as possible to the intention, when the exact one fails' },
  { text: 'Damnum emergens.', attrib: 'The loss actually suffered' },
  { text: 'Lucrum cessans.', attrib: 'The profit prevented' },
  { text: 'Habeas corpus.', attrib: 'That you have the body — produce the person' },
  { text: 'Mandamus.', attrib: 'We command — an order to do a public duty' },
  { text: 'Quo warranto.', attrib: 'By what authority do you hold this office' },
  { text: 'Certiorari.', attrib: 'To be certified — bring up the record for review' },
  { text: 'Nemo potest esse simul actor et judex.', attrib: 'No one can be at once the suitor and the judge' },
  { text: 'Actus curiae neminem gravabit.', attrib: 'An act of the court shall prejudice no one' },
  { text: 'Lex non cogit ad impossibilia.', attrib: 'The law does not compel the impossible' },
  { text: 'Nemo moriturus praesumitur mentiri.', attrib: 'No one at the point of death is presumed to lie' },
  { text: 'Qui tacet consentire videtur.', attrib: 'He who is silent is taken to consent' },
  { text: 'Injuria non excusat injuriam.', attrib: 'One wrong does not excuse another' },
  { text: 'Ubi non est principalis, non potest esse accessorius.', attrib: 'Where there is no principal, there can be no accessory' },
  { text: 'Bona fide.', attrib: 'In good faith, honestly and without notice' },
  { text: 'Amicus curiae.', attrib: 'A friend of the court, assisting rather than appearing' },
  { text: 'Animus possidendi.', attrib: 'The intention to possess, without which possession is nothing' },
  { text: 'Ad idem.', attrib: 'Of one mind — the meeting that makes a contract' },
  { text: 'Inter alia.', attrib: 'Among other things' },
  { text: 'Modus operandi.', attrib: 'The manner of working' },
  { text: 'De facto.', attrib: 'In fact, whatever the paper says' },
  { text: 'De jure.', attrib: 'By law, whatever the facts say' },
  { text: 'Ferae naturae.', attrib: 'Of a wild nature, and so owned by no one' },
  { text: 'Communis error facit jus.', attrib: 'A common error, long acted on, can make law' },
]
