// The working life — clients, fees, seniors, chambers, courts, ethics
// and the study habit. Deliberately about conduct rather than doctrine,
// so nothing here goes stale with an amendment. 90 entries.

export const PRACTICE = [
  'Confirm the brief in writing. Memory is not a retainer.',
  'Agree the fee before the work, not after the result.',
  'A client who cannot pay today may be your best referral in five years.',
  'Keep client money separate from your own. There is no small exception.',
  'Return the file when the engagement ends, and keep a copy of the index.',
  'A conflict check takes four minutes and saves four years.',
  'Never act against a former client on a matter you learned from.',
  'Say no to the matter outside your competence, then find them someone good.',
  'Tell the client the worst outcome at the first meeting, not the last.',
  'Put advice in writing. Oral advice becomes something else in a client’s memory.',
  'Give a realistic timeline. Then add the adjournments you know are coming.',
  'Explain what the next hearing is actually for. Most clients never get told.',
  'Call the client after the hearing, even when there is nothing to report.',
  'A client who understands the delay complains far less about the delay.',
  'Never guarantee an outcome. Not once, not casually, not to family.',
  'Bill promptly. A stale invoice is an awkward conversation waiting to happen.',
  'Record time as you work. Reconstructing a week is guesswork and you know it.',
  'Keep an attendance note of every substantive call. It is your best defence.',
  'Diary the limitation date the day the file opens.',
  'Diary the next date before you leave the court complex.',
  'Two diaries, or one you actually trust. Not zero.',
  'Reconcile the cause list against your diary the evening before.',
  'Arrive before your matter is called. Reputations are built in the first row.',
  'Dress for the court you are in. It is a courtesy, not a costume.',
  'Address the bench, not the opponent. Even when provoked.',
  'Never interrupt the court. Wait, then make the point better.',
  'If you are wrong, say so at once. The correction costs less than the pretence.',
  'Do not mislead the court on fact or on law, even by silence.',
  'Cite the authority against you. The other side will, and less kindly.',
  'Be scrupulous about what you tell the registry. They remember.',
  'Learn the names of the court staff. They will save you one day.',
  'Thank the clerk who found your file. It is a small profession.',
  'The stenographer is recording what you said, not what you meant. Speak clearly.',
  'Ask for the order copy the same day. Chasing it later costs a week.',
  'Read the order you obtained. It rarely says exactly what you asked for.',
  'Check the decretal portion against the reasoning before you certify satisfaction.',
  'Diarise the appeal period the day the order comes.',
  'Explain the order to the client in one paragraph of plain language.',
  'Keep a personal note of what worked in each hearing. Nobody else will.',
  'Watch a senior you admire argue, at least once a month.',
  'Sit through a matter that is nothing to do with you. It is the cheapest education.',
  'Read one full judgment a week, not just the headnote.',
  'The headnote is somebody’s summary. The ratio is yours to find.',
  'Subscribe to one reliable reporter and actually open it.',
  'Track amendments in the statutes you use most. They change quietly.',
  'Keep a bare Act in your bag. Search results are not a substitute.',
  'Learn one new procedure properly each quarter.',
  'Teach something to a junior. You will find out what you do not know.',
  'Join one bar association activity a year. Isolation ends careers quietly.',
  'Find a mentor and be honest with them about what you cannot do.',
  'Be the person who answers the junior’s message.',
  'Credit the junior who found the point, in front of the client.',
  'Pay your juniors on time. They remember it for a lifetime.',
  'Never ask a junior to do something you would not sign your name to.',
  'The intern is watching how you speak to the office staff.',
  'A chamber with a good library and bad manners produces bad lawyers.',
  'Do not gossip about a judge. It reaches further than you think.',
  'Do not gossip about a client. Ever, and not in a lift.',
  'Confidentiality survives the engagement. It survives the client, too.',
  'Do not discuss matters in the corridor. Corridors carry.',
  'Back up your files. A lost drive is a professional negligence claim.',
  'Password-protect anything that leaves the office.',
  'Do not send a draft to the wrong email. Check the address before the attachment.',
  'Encrypt or courier the sensitive thing. Convenience is not a defence.',
  'Keep a written engagement letter even for a friend. Especially for a friend.',
  'Do not take a matter you cannot service. Overcommitment is a form of harm.',
  'Turn down work when the diary is full. The refusal protects the client.',
  'Professional indemnity cover is not pessimism, it is competence.',
  'Know your own limitation period for suing on unpaid fees.',
  'Keep your enrolment and certificate of practice current. Diarise the renewal.',
  'Attend to your own compliance the way you attend to a client’s.',
  'File your own returns on time. It is an odd thing to be bad at.',
  'Take a holiday. The docket does not thank you for the ones you skipped.',
  'Exercise, sleep, and eat before a long hearing. Advocacy is physical.',
  'If the work is affecting your health, that is a professional problem, not a private one.',
  'Talk to someone when a matter is weighing on you. Others carry the same.',
  'A profession with this much responsibility must also have limits. Set yours.',
  'Do the pro bono matter. It will remind you what the licence is for.',
  'Legal aid work is not lesser work. Prepare it the same.',
  'Explain the law for free when someone asks in good faith. It costs a minute.',
  'You will be asked for a favour that shades into impropriety. Practise saying no.',
  'When a client asks you to backdate anything, the answer is no.',
  'When a client hides a document, tell them why that ends the engagement.',
  'Do not lend your signature to a document you have not read.',
  'Do not certify what you have not verified.',
  'Your seal and your signature are the only assets that cannot be replaced.',
  'Integrity is a compounding asset. So is its absence.',
  'Leave the profession better indexed than you found it: write your notes clearly.',
  'Keep a record of every matter you have argued. Careers are built from evidence.',
  'One day someone will ask you how to start. Have a real answer ready.',
]
