/** Sample generated content, used by the New Draft generation/result screens and DraftDetailScreen. */
export const SAMPLE_LEGAL_NOTICE = `To,
Mr. Rohan Kapoor
14, Palm Grove Society, Andheri West, Mumbai \u2013 400058

UNDER INSTRUCTIONS from and on behalf of my client, Mrs. Sunita Mehta, residing at 22, Sea View Apartments, Bandra West, Mumbai, I hereby serve upon you the following legal notice:

1. That my client is the lawful and registered owner of the residential flat No. 402, situated at Sunshine Apartments, Andheri West, Mumbai (\u201cthe Property\u201d), having purchased the same vide registered Sale Deed dated 12.03.2016.

2. That you have, without any right, title or lawful authority, encroached upon a portion of the Property measuring approximately 180 sq. ft. adjoining the common passage, and have unlawfully constructed a permanent structure thereon.

3. That despite repeated requests made by my client, both orally and in writing, you have failed and neglected to remove the said encroachment.

YOU ARE THEREFORE CALLED UPON to remove the encroachment and restore vacant and peaceful possession of the Property to my client within 15 (fifteen) days of receipt of this notice, failing which my client shall be constrained to initiate appropriate civil and criminal proceedings against you, entirely at your risk, cost and consequences.

A copy of this notice is retained in my office for record and further necessary action.`;

export type DraftVersion = { label: string; meta: string; note: string; dotColor: string };

export const SAMPLE_VERSION_HISTORY: DraftVersion[] = [
  { label: 'Version 3 (current)', meta: 'Edited by you \u00b7 2 hours ago', note: 'Revised clause 3 \u2014 added timeline for compliance.', dotColor: '#D4A017' },
  { label: 'Version 2', meta: 'Edited by you \u00b7 Yesterday, 6:40 PM', note: 'AI regeneration with updated encroachment measurements.', dotColor: '#3FA66B' },
  { label: 'Version 1 \u2014 Original draft', meta: 'Generated by AI \u00b7 3 days ago', note: 'Initial draft generated from intake form.', dotColor: '#6E6E68' },
];
