import Groq from 'groq-sdk'

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

const PROMPTS = {
  LEGAL_NOTICE: 'You are an expert Indian legal professional. Generate a complete, professional Legal Notice with proper formatting, sender/recipient details, legal basis with relevant sections of Indian law, specific grievances, remedy demanded, and a 15-day deadline. Use formal legal language.',
  CASE_BRIEF: 'You are a senior Indian advocate. Generate a comprehensive Case Brief including: case summary, facts, legal issues raised, arguments for both sides, relevant case laws and Indian precedents, and legal analysis.',
  CONTRACT: 'You are an expert contract lawyer in India. Draft a comprehensive legal Contract with: parties, recitals, definitions, obligations, payment terms, termination clauses, dispute resolution, governing law (India), and signature blocks.',
  PETITION: 'You are a senior advocate in India. Draft a formal Petition with: court addressing, petitioner/respondent details, jurisdictional facts, statement of facts, legal grounds, prayer/relief sought, verification, and proper legal citations.',
  MEMORANDUM: 'You are an Indian legal expert. Draft a professional Legal Memorandum with: header, executive summary, background, legal analysis with relevant Indian laws and precedents, conclusions, and actionable recommendations.',
}

export async function generateLegalDocument(documentType, details) {
  const systemPrompt = PROMPTS[documentType] || PROMPTS.LEGAL_NOTICE
  try {
    const completion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Generate a complete ${documentType.replace(/_/g,' ')} with these details:\n\n${details}\n\nMake it thorough, professional, and legally sound under Indian law.` },
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.3,
      max_tokens: 3000,
    })
    return completion.choices[0]?.message?.content || fallback(documentType, details)
  } catch (err) {
    console.error('Groq error:', err)
    return fallback(documentType, details)
  }
}

export async function analyzeLegalIssue(issue) {
  try {
    const completion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: 'You are an expert Indian legal analyst. Analyze legal issues with: 1) Brief analysis, 2) Relevant Indian laws/sections, 3) Key case laws with citations, 4) Recommended course of action. Be precise and practical.' },
        { role: 'user', content: `Analyze this legal issue under Indian law:\n\n${issue}` },
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.2,
      max_tokens: 1500,
    })
    return completion.choices[0]?.message?.content || 'Analysis unavailable. Please check your API key.'
  } catch (err) {
    console.error('Groq error:', err)
    return 'Analysis unavailable. Please check your GROQ_API_KEY.'
  }
}

function fallback(type, details) {
  const date = new Date().toLocaleDateString('en-IN', { year:'numeric', month:'long', day:'numeric' })
  return `${type.replace(/_/g,' ')}\n\nDate: ${date}\n\n${details}\n\n[AI generation unavailable. Please check your GROQ_API_KEY in .env.local]\n\nGenerated by LexForge AI`
}
