import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'

export async function GET(req, { params }) {
  try {
    const session = await auth()
    if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { id, format } = await params
    if (!['pdf', 'docx', 'txt'].includes(format))
      return NextResponse.json({ error: 'Invalid format. Use: pdf, docx, txt' }, { status: 400 })

    const { prisma } = await import('@/lib/prisma')
    const draft = await prisma.draft.findFirst({ where: { id, userId: session.user.id } })
    if (!draft) return NextResponse.json({ error: 'Document not found.' }, { status: 404 })

    const safeName = draft.title.replace(/[^a-z0-9]/gi, '_').substring(0, 50)
    const dateStr = new Date(draft.createdAt).toLocaleDateString('en-IN')

    // ── TXT ──────────────────────────────────────────
    if (format === 'txt') {
      const text = [
        draft.title,
        '='.repeat(60),
        `Type: ${draft.documentType.replace(/_/g, ' ')}`,
        `Status: ${draft.status}`,
        `Date: ${dateStr}`,
        '',
        '─'.repeat(60),
        '',
        draft.content,
        '',
        '─'.repeat(60),
        'Generated by LexForge AI',
      ].join('\n')

      return new NextResponse(text, {
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Content-Disposition': `attachment; filename="${safeName}.txt"`,
        },
      })
    }

    // ── DOCX ─────────────────────────────────────────
    if (format === 'docx') {
      const { Document, Paragraph, TextRun, HeadingLevel, Packer } = await import('docx')
      const doc = new Document({
        sections: [{
          children: [
            new Paragraph({ text: draft.title, heading: HeadingLevel.HEADING_1 }),
            new Paragraph({ children: [new TextRun({ text: 'Type: ', bold: true }), new TextRun(draft.documentType.replace(/_/g, ' '))] }),
            new Paragraph({ children: [new TextRun({ text: 'Status: ', bold: true }), new TextRun(draft.status)] }),
            new Paragraph({ children: [new TextRun({ text: 'Date: ', bold: true }), new TextRun(dateStr)] }),
            new Paragraph({ text: '' }),
            ...draft.content.split('\n').map(line =>
              new Paragraph({ children: [new TextRun({ text: line || ' ' })] })
            ),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun({ text: 'Generated by LexForge AI', italics: true, color: '888888' })] }),
          ],
        }],
      })
      const buf = await Packer.toBuffer(doc)
      return new NextResponse(buf, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${safeName}.docx"`,
        },
      })
    }

    // ── PDF ──────────────────────────────────────────
    if (format === 'pdf') {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })
      const margin = 20
      const maxW = doc.internal.pageSize.getWidth() - margin * 2
      let y = 20

      const checkPage = (space = 8) => { if (y + space > 275) { doc.addPage(); y = 20 } }

      // Title
      doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(40, 40, 40)
      doc.splitTextToSize(draft.title, maxW).forEach(line => {
        checkPage(9); doc.text(line, margin, y); y += 9
      })
      y += 3

      // Meta
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(120, 120, 120)
      ;[`Type: ${draft.documentType.replace(/_/g, ' ')}`, `Status: ${draft.status}`, `Date: ${dateStr}`]
        .forEach(line => { checkPage(6); doc.text(line, margin, y); y += 6 })
      y += 3

      // Divider
      doc.setDrawColor(200, 200, 200)
      doc.line(margin, y, doc.internal.pageSize.getWidth() - margin, y); y += 8

      // Content
      doc.setFontSize(11); doc.setTextColor(40, 40, 40)
      doc.splitTextToSize(draft.content, maxW).forEach(line => {
        checkPage(6); doc.text(line, margin, y); y += 6
      })

      // Footer
      y += 8; checkPage(6)
      doc.setFontSize(9); doc.setTextColor(160, 160, 160)
      doc.text('Generated by LexForge AI', margin, y)

      return new NextResponse(Buffer.from(doc.output('arraybuffer')), {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${safeName}.pdf"`,
        },
      })
    }
  } catch (err) {
    console.error('[GET /api/export]', err)
    return NextResponse.json({ error: `Export failed: ${err?.message}` }, { status: 500 })
  }
}
