import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'

export async function GET(req, { params }) {
  try {
    const session = await auth()
    if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { id, format } = await params
    if (!['pdf', 'docx', 'txt'].includes(format))
      return NextResponse.json({ error: 'Invalid format. Use: pdf, docx, txt' }, { status: 400 })

    const { prisma } = await import('@/lib/prisma')
    const draft = await prisma.draft.findFirst({ where: { id, userId: session.user.id } })
    if (!draft) return NextResponse.json({ error: 'Document not found.' }, { status: 404 })

    const safeName = draft.title.replace(/[^a-z0-9]/gi, '_').substring(0, 50)
    const dateStr = new Date(draft.createdAt).toLocaleDateString('en-IN')

    // ── Helper: parse legalReasoning into structured sections ──────
    function parseMeritsDemerits(legalReasoning) {
      if (!legalReasoning) return null
      const sections = {}
      const sectionHeaders = ['MERITS', 'DEMERITS', 'LEGAL RISKS', 'RECOMMENDATIONS']
      let current = null
      for (const line of legalReasoning.split('\n')) {
        const clean = line.trim()
        const header = sectionHeaders.find(h => clean.replace(/#+\s*/,'').toUpperCase().startsWith(h))
        if (header) { current = header; sections[header] = []; continue }
        if (current && clean && !clean.startsWith('---')) {
          // Strip markdown bullets
          const stripped = clean.replace(/^[-*•]\s*/, '').replace(/^\d+\.\s*/, '')
          if (stripped) sections[current].push(stripped)
        }
      }
      return Object.keys(sections).length > 0 ? sections : null
    }

    // ── TXT ──────────────────────────────────────────
    if (format === 'txt') {
      const conclusionBlock = draft.legalReasoning
        ? ['\n' + '─'.repeat(60), '\nCONCLUSION — LEGAL ANALYSIS', '─'.repeat(60), '', draft.legalReasoning, '']
        : []

      const text = [
        draft.title,
        '='.repeat(60),
        `Type: ${draft.documentType.replace(/_/g, ' ')}`,
        `Status: ${draft.status}`,
        `Date: ${dateStr}`,
        '',
        '─'.repeat(60),
        '',
        draft.content,
        '',
        ...conclusionBlock,
        '─'.repeat(60),
        'Generated by LexForge AI',
      ].join('\n')

      return new NextResponse(text, {
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Content-Disposition': `attachment; filename="${safeName}.txt"`,
        },
      })
    }

    // ── DOCX ─────────────────────────────────────────
    if (format === 'docx') {
      const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Packer } = await import('docx')

      // Build conclusion paragraphs
      const conclusionParagraphs = []
      if (draft.legalReasoning) {
        conclusionParagraphs.push(new Paragraph({ text: '' }))
        // Horizontal rule via border paragraph
        conclusionParagraphs.push(new Paragraph({
          border: { top: { value: BorderStyle.SINGLE, size: 6, color: 'C0A020' } },
          text: '',
        }))
        conclusionParagraphs.push(new Paragraph({
          text: 'CONCLUSION — LEGAL ANALYSIS',
          heading: HeadingLevel.HEADING_2,
        }))
        conclusionParagraphs.push(new Paragraph({
          children: [new TextRun({ text: 'AI-generated merits & demerits analysis for advocate and client reference.', italics: true, color: '888888', size: 18 })],
        }))
        conclusionParagraphs.push(new Paragraph({ text: '' }))

        const parsed = parseMeritsDemerits(draft.legalReasoning)
        if (parsed) {
          const sectionColors = { MERITS: '2E7D32', DEMERITS: 'C62828', 'LEGAL RISKS': 'E65100', RECOMMENDATIONS: '1565C0' }
          const sectionIcons  = { MERITS: '✅ ', DEMERITS: '❌ ', 'LEGAL RISKS': '⚠️  ', RECOMMENDATIONS: '💡 ' }
          for (const [sec, items] of Object.entries(parsed)) {
            conclusionParagraphs.push(new Paragraph({
              children: [new TextRun({ text: (sectionIcons[sec] || '') + sec, bold: true, color: sectionColors[sec] || '333333', size: 24 })],
              spacing: { before: 200, after: 80 },
            }))
            items.forEach((item, idx) => {
              conclusionParagraphs.push(new Paragraph({
                children: [new TextRun({ text: `${idx + 1}. ${item}`, size: 20 })],
                indent: { left: 360 },
                spacing: { after: 60 },
              }))
            })
          }
        } else {
          // Fallback: render raw text
          draft.legalReasoning.split('\n').forEach(line => {
            conclusionParagraphs.push(new Paragraph({ children: [new TextRun({ text: line || ' ', size: 20 })] }))
          })
        }
      }

      const doc = new Document({
        sections: [{
          children: [
            new Paragraph({ text: draft.title, heading: HeadingLevel.HEADING_1 }),
            new Paragraph({ children: [new TextRun({ text: 'Type: ', bold: true }), new TextRun(draft.documentType.replace(/_/g, ' '))] }),
            new Paragraph({ children: [new TextRun({ text: 'Status: ', bold: true }), new TextRun(draft.status)] }),
            new Paragraph({ children: [new TextRun({ text: 'Date: ', bold: true }), new TextRun(dateStr)] }),
            new Paragraph({ text: '' }),
            ...draft.content.split('\n').map(line =>
              new Paragraph({ children: [new TextRun({ text: line || ' ' })] })
            ),
            ...conclusionParagraphs,
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun({ text: 'Generated by LexForge AI', italics: true, color: '888888' })] }),
          ],
        }],
      })
      const buf = await Packer.toBuffer(doc)
      return new NextResponse(buf, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${safeName}.docx"`,
        },
      })
    }

    // ── PDF ──────────────────────────────────────────
    if (format === 'pdf') {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })
      const margin = 20
      const maxW = doc.internal.pageSize.getWidth() - margin * 2
      let y = 20

      const checkPage = (space = 8) => { if (y + space > 275) { doc.addPage(); y = 20 } }

      // Title
      doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(40, 40, 40)
      doc.splitTextToSize(draft.title, maxW).forEach(line => {
        checkPage(9); doc.text(line, margin, y); y += 9
      })
      y += 3

      // Meta
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(120, 120, 120)
      ;[`Type: ${draft.documentType.replace(/_/g, ' ')}`, `Status: ${draft.status}`, `Date: ${dateStr}`]
        .forEach(line => { checkPage(6); doc.text(line, margin, y); y += 6 })
      y += 3

      // Divider
      doc.setDrawColor(200, 200, 200)
      doc.line(margin, y, doc.internal.pageSize.getWidth() - margin, y); y += 8

      // Content
      doc.setFontSize(11); doc.setFont('helvetica', 'normal'); doc.setTextColor(40, 40, 40)
      doc.splitTextToSize(draft.content, maxW).forEach(line => {
        checkPage(6); doc.text(line, margin, y); y += 6
      })

      // ── Conclusion — Legal Analysis ──────────────────────────────
      if (draft.legalReasoning) {
        y += 6; checkPage(20)

        // Gold divider
        doc.setDrawColor(212, 160, 23)
        doc.setLineWidth(0.6)
        doc.line(margin, y, doc.internal.pageSize.getWidth() - margin, y)
        doc.setLineWidth(0.2); y += 8

        // Section heading
        doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(212, 160, 23)
        doc.text('CONCLUSION — LEGAL ANALYSIS', margin, y); y += 6
        doc.setFontSize(9); doc.setFont('helvetica', 'italic'); doc.setTextColor(140, 140, 140)
        doc.text('AI-generated merits & demerits analysis for advocate and client reference.', margin, y); y += 8

        const parsed = parseMeritsDemerits(draft.legalReasoning)
        if (parsed) {
          const sectionColors = {
            MERITS:          [46, 125, 50],
            DEMERITS:        [198, 40, 40],
            'LEGAL RISKS':   [230, 81, 0],
            RECOMMENDATIONS: [21, 101, 192],
          }
          for (const [sec, items] of Object.entries(parsed)) {
            checkPage(12)
            const [r, g, b] = sectionColors[sec] || [60, 60, 60]
            doc.setFontSize(11); doc.setFont('helvetica', 'bold'); doc.setTextColor(r, g, b)
            doc.text(sec, margin, y); y += 6

            doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60)
            items.forEach((item, idx) => {
              const lines = doc.splitTextToSize(`${idx + 1}. ${item}`, maxW - 8)
              lines.forEach(line => { checkPage(5.5); doc.text(line, margin + 4, y); y += 5.5 })
            })
            y += 3
          }
        } else {
          // Raw fallback
          doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60)
          doc.splitTextToSize(draft.legalReasoning, maxW).forEach(line => {
            checkPage(5.5); doc.text(line, margin, y); y += 5.5
          })
        }
      }

      // Footer
      y += 8; checkPage(6)
      doc.setFontSize(9); doc.setFont('helvetica', 'italic'); doc.setTextColor(160, 160, 160)
      doc.text('Generated by LexForge AI', margin, y)

      return new NextResponse(Buffer.from(doc.output('arraybuffer')), {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${safeName}.pdf"`,
        },
      })
    }
  } catch (err) {
    console.error('[GET /api/export]', err)
    return NextResponse.json({ error: `Export failed: ${err?.message}` }, { status: 500 })
  }
}
